export const products = [
    {
        id: 1,
        type: "pizza",
        name: "Salami",
        price: 10,
        size: '',
        inCart: false,
        count: 0,
        total: 0,
        ingredientsUsed: [{"pepperoni": 4}],
    },
    {
        id: 2,
        type: "pizza",
        name: "Margherita",
        price: 10,
        size: '',
        inCart: false,
        count: 0,
        total: 0,
        ingredientsUsed: [{"cheese": 0.25}],
    },
    {
        id: 3,
        type: "drink",
        name: "Cola",
        price: 2.50,
        size: '',
        inCart: false,
        count: 0,
        total: 0,
        ingredientsUsed: [{"cola": 0.25}],
    }
];